### ISSUE TITLE
Conflicting namespace with orm

### ISSUE THREAD

**Issue by cgwin** [doctrine/mongodb-odm-softdelete-bundle#3]
We are implementing the odm and the orm. The namespaces with the softdelete bundle in this setup create a conflict since the orm setups the doctorine name space in a different location then the softdelete bundle. Which ever is listed first will win out.

**Comment by jmikola** [comment]
This bundle uses the `Doctrine\Bundle\MongoDBSoftDeleteBundle` namespace, which doesn't conflict with anything in ORM. If you examine [composer.json](https://github.com/doctrine/mongodb-odm-softdelete-bundle/blob/master/composer.json), you'll see that autoloading should be configured for the full namespace.

I assume you're not using composer, but feel free to share your autoloader file and I can point out a solution.
